name: Run Pytest Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Skip CI
        run: echo "Skipping tests" && exit 0

# jobs:
#   test:
#     runs-on: ${{ matrix.os }}

#     strategy:
#       matrix:
#         os: [ubuntu-latest, macos-latest, windows-latest]
#         python-version: ["3.10"]

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v4
#         with:
#           submodules: recursive  # Ensures all submodules are checked out

#       - name: Set Up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: ${{ matrix.python-version }}

#       - name: Install Dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install toddlerbot/brax
#           pip install ".[test]"

#       - name: Run Tests
#         run: pytest tests/